name: ml_sessions_2022
channels:
- conda-forge
dependencies:
- python=3.9.7
- matplotlib=3.5.2
- numpy=1.19.5
- pandas=1.4.1
- scikit-learn=1.0.2
- seaborn=0.11.2
- openpyxl=3.0.9
- imbalanced-learn=0.9.0  
- jupyter=1.0.0
- lightgbm=3.3.2